# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
        # exclude: '^\.devcontainer/devcontainer\.json$'
        exclude: ^(\.devcontainer/devcontainer.json|react-admin/tsconfig.app.json)
      - id: end-of-file-fixer
        exclude: '^\.devcontainer/devcontainer\.json$'
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: no-commit-to-branch
