volumes:
  # use named volume to persist data, in this case the database
  pgdata:
  node_modules:
  ishelters:


secrets:
  # share senstive info without exposing them via environment variables
  secret_key:
    environment: SECRET_KEY
  postgres_user:
    environment: POSTGRES_USER
  postgres_db:
    environment: POSTGRES_DATABASE
  postgres_passwd:
    environment: POSTGRES_PASSWORD
  email_user:
    environment: EMAIL_USER
  email_password:
    environment: EMAIL_PASSWORD

services:
  # See https://hub.docker.com/_/postgres
  database:
    image: postgres
    container_name: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_passwd
      - TZ=${GLOBAL_TIMEZONE:-America/New_York}
    secrets:
      - postgres_db
      - postgres_user
      - postgres_passwd
    #Healthcheck for database
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$$POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  django:
    working_dir: /app
    volumes:
      # The defaults value . is added so that the docker-compose.yaml file can
      # work when running docker-outside-of-docker in devcontainer
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    image: aau-vms-backend
    container_name: django
    secrets:
      - secret_key
      - postgres_db
      - postgres_user
      - postgres_passwd
      - email_user
      - email_password
    depends_on:
      - database
    environment:
      - TZ=${GLOBAL_TIMEZONE:-America/New_York}
      # SECURITY WARNING: don't run with debug turned on in production!
      - DEBUG=${DEBUG:-False}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}
      #region Email configuration
      # Gmail SMTP: https://support.google.com/a/answer/176600?hl=en - Option 2
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_TIMEOUT=${EMAIL_TIMEOUT:-60}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-False}
      # Including a trailing space so appended text is not squished
      - EMAIL_SUBJECT_PREFIX=${EMAIL_SUBJECT_PREFIX:-AAU VMS }
      - DEFAULT_FROM_EMAIL=${EMAIL_DEFAULT_FROM:-aauvms@localhost}
      #endregion
    ports:
      - ${DJANGO_PORT:-8000}:8000
    entrypoint: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    #Healthcheck for django
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  react-admin:
    image: aau-vms-frontend
    container_name: react
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_JSON_SERVER_URL=${VITE_JSON_SERVER_URL:-http://localhost:${DJANGO_PORT:-8000}}
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.env:/app/.env
      - ${LOCAL_WORKSPACE_FOLDER:-.}/react-admin:/app
      # https://github.com/vitejs/vite/discussions/15532#discussioncomment-8038794
      # - node_modules:/app/node_modules
    ports:
      - ${VITE_PORT:-80}:5173
    depends_on:
      - database
      - django
    #Healthcheck for react-admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ishelters:
    image: mysql
    container_name: aau_ishelters
    environment:
      MYSQL_DATABASE: aau_ishelters
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ishelters:/var/lib/mysql
      - ${LOCAL_WORKSPACE_FOLDER:-.}/docker_init/ishelters:/docker-entrypoint-initdb.d
    depends_on:
      - database
      - django
      - react-admin
