volumes:
  # use named volume to persist data, in this case the database
  pgdata:
  node_modules:


secrets:
  # share senstive info without exposing them via environment variables
  secret_key:
    environment: SECRET_KEY
  postgres_user:
    environment: POSTGRES_USER
  postgres_db:
    environment: POSTGRES_DATABASE
  postgres_passwd:
    environment: POSTGRES_PASSWORD

services:
  # See https://hub.docker.com/_/postgres
  database:
    image: postgres
    container_name: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_passwd
      - TZ=${GLOBAL_TIMEZONE:-America/New_York}
    secrets:
      - postgres_db
      - postgres_user
      - postgres_passwd
  django:
    working_dir: /app
    volumes:
      # The defaults value . is added so that the docker-compose.yaml file can
      # work when running docker-outside-of-docker in devcontainer
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    image: aau-vms-backend
    container_name: django
    secrets:
      - secret_key
      - postgres_db
      - postgres_user
      - postgres_passwd
    environment:
      - TZ=${GLOBAL_TIMEZONE:-America/New_York}
      # SECURITY WARNING: don't run with debug turned on in production!
      - DEBUG=${DEBUG:-True}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}
    ports:
      - ${DJANGO_PORT:-8000}:8000
    entrypoint: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
  react-admin:
    image: aau-vms-frontend
    container_name: react
    environment:
      - VITE_JSON_SERVER_URL=${VITE_JSON_SERVER_URL:-http://localhost:${DJANGO_PORT:-8000}}
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.env:/app/.env
      - ${LOCAL_WORKSPACE_FOLDER:-.}/react-admin:/app
      # https://github.com/vitejs/vite/discussions/15532#discussioncomment-8038794
      - node_modules:/app/node_modules
    ports:
      - ${VITE_PORT:-80}:5173
