# Generated by Django 5.1.1 on 2024-10-29 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=155)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('active_status_change_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cell_phone', models.CharField(max_length=128)),
                ('home_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(default='AAU Volunteer', null=True)),
                ('ishelters_id', models.IntegerField(editable=False, unique=True)),
                ('maddie_certifications_received_date', models.DateField(blank=True, null=True)),
                ('has_maddie_certifications', models.BooleanField(default=False)),
                ('ishelters_created_dt', models.DateTimeField(editable=False, null=True)),
                ('application_received_date', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ishelters_id', models.IntegerField(editable=False, unique=True)),
                ('ishelters_created_dt', models.DateTimeField(editable=False, null=True)),
                ('application_received_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email',), name='email_null_not_unique', nulls_distinct=True)],
            },
        ),
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(null=True)),
                ('activity_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=50)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_date', models.DateField()),
                ('years_of_service', models.IntegerField(default=0)),
                ('award_title', models.CharField(blank=True, max_length=100, null=True)),
                ('award_description', models.TextField(blank=True, null=True)),
                ('achievement_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(default=1, help_text='Skill proficiency level from 0 to 10')),
                ('years_of_experience', models.DecimalField(decimal_places=1, help_text='Years of experience in this skill', max_digits=4)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the skill', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(db_column='volunteer_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('application_received_date', models.DateTimeField(auto_now=True)),
                ('ishelters_id', models.IntegerField(editable=False, unique=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('volunteer', models.ForeignKey(db_column='volunteer_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
    ]
