# Generated by Django 5.1.1 on 2024-10-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerteam',
            name='team',
            field=models.ForeignKey(db_column='team_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
