# Generated by Django 5.1.1 on 2024-10-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_volunteerteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
