# Generated by Django 5.1.1 on 2024-10-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_county_ishelters_id_alter_county_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteermilestone',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.ForeignKey(db_column='address_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
        migrations.AlterField(
            model_name='volunteermilestone',
            name='achievement_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
        ),
    ]
