# Generated by Django 5.1.1 on 2024-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_volunteermilestone_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='has_maddie_certifications',
            field=models.BooleanField(default=False),
        ),
    ]
