# Generated by Django 5.1.1 on 2024-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_volunteer_has_maddie_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='county',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
