# Generated by Django 5.1.1 on 2024-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_volunteer_address_line_1_alter_volunteer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerskill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='volunteerskill',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
