# Generated by Django 5.1.1 on 2024-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_volunteerskill_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='hours_spent',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='status',
        ),
        migrations.AlterField(
            model_name='volunteeractivity',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
