# Generated by Django 5.1.1 on 2024-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_volunteerchildren_volunteerpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerchildren',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteerchildren',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteerpet',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteerpet',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
