export const ENDPOINTS = {
  TEAMS: "teams",
  USERS: "users",
  VOLUNTEERS: "volunteers",
  SKILLS_CATEGORIES: "skills-categories",
  VOLUNTEER_ACTIVITIES: "VOLUNTEER_ACTIVITIES",
}

export const API_BASE_URL=import.meta.env.VITE_JSON_SERVER_URL

interface County {
  id: string
  name: string
}

export const GA_COUNTIES: County[] = [
  {id: "undefined", name: "No address"},
  {id: "Appling", name: "Appling"},
  {id: "Atkinson", name: "Atkinson"},
  {id: "Bacon", name: "Bacon"},
  {id: "Baker", name: "Baker"},
  {id: "Baldwin", name: "Baldwin"},
  {id: "Banks", name: "Banks"},
  {id: "Barrow", name: "Barrow"},
  {id: "Bartow", name: "Bartow"},
  {id: "Ben Hill", name: "Ben Hill"},
  {id: "Berrien", name: "Berrien"},
  {id: "Bibb", name: "Bibb"},
  {id: "Bleckley", name: "Bleckley"},
  {id: "Brantley", name: "Brantley"},
  {id: "Brooks", name: "Brooks"},
  {id: "Bryan", name: "Bryan"},
  {id: "Bulloch", name: "Bulloch"},
  {id: "Burke", name: "Burke"},
  {id: "Butts", name: "Butts"},
  {id: "Calhoun", name: "Calhoun"},
  {id: "Camden", name: "Camden"},
  {id: "Candler", name: "Candler"},
  {id: "Carroll", name: "Carroll"},
  {id: "Catoosa", name: "Catoosa"},
  {id: "Charlton", name: "Charlton"},
  {id: "Chatham", name: "Chatham"},
  {id: "Chattahoochee", name: "Chattahoochee"},
  {id: "Chattooga", name: "Chattooga"},
  {id: "Cherokee", name: "Cherokee"},
  {id: "Clarke", name: "Clarke"},
  {id: "Clay", name: "Clay"},
  {id: "Clayton", name: "Clayton"},
  {id: "Clinch", name: "Clinch"},
  {id: "Cobb", name: "Cobb"},
  {id: "Coffee", name: "Coffee"},
  {id: "Colquitt", name: "Colquitt"},
  {id: "Columbia", name: "Columbia"},
  {id: "Cook", name: "Cook"},
  {id: "Coweta", name: "Coweta"},
  {id: "Crawford", name: "Crawford"},
  {id: "Crisp", name: "Crisp"},
  {id: "Dade", name: "Dade"},
  {id: "Dawson", name: "Dawson"},
  {id: "Decatur", name: "Decatur"},
  {id: "DeKalb", name: "DeKalb"},
  {id: "Dodge", name: "Dodge"},
  {id: "Dooly", name: "Dooly"},
  {id: "Dougherty", name: "Dougherty"},
  {id: "Douglas", name: "Douglas"},
  {id: "Early", name: "Early"},
  {id: "Echols", name: "Echols"},
  {id: "Effingham", name: "Effingham"},
  {id: "Elbert", name: "Elbert"},
  {id: "Emanuel", name: "Emanuel"},
  {id: "Evans", name: "Evans"},
  {id: "Fannin", name: "Fannin"},
  {id: "Fayette", name: "Fayette"},
  {id: "Floyd", name: "Floyd"},
  {id: "Forsyth", name: "Forsyth"},
  {id: "Franklin", name: "Franklin"},
  {id: "Fulton", name: "Fulton"},
  {id: "Gilmer", name: "Gilmer"},
  {id: "Glascock", name: "Glascock"},
  {id: "Glynn", name: "Glynn"},
  {id: "Gordon", name: "Gordon"},
  {id: "Grady", name: "Grady"},
  {id: "Greene", name: "Greene"},
  {id: "Gwinnett", name: "Gwinnett"},
  {id: "Habersham", name: "Habersham"},
  {id: "Hall", name: "Hall"},
  {id: "Hancock", name: "Hancock"},
  {id: "Haralson", name: "Haralson"},
  {id: "Harris", name: "Harris"},
  {id: "Hart", name: "Hart"},
  {id: "Heard", name: "Heard"},
  {id: "Henry", name: "Henry"},
  {id: "Houston", name: "Houston"},
  {id: "Irwin", name: "Irwin"},
  {id: "Jackson", name: "Jackson"},
  {id: "Jasper", name: "Jasper"},
  {id: "Jeff Davis", name: "Jeff Davis"},
  {id: "Jefferson", name: "Jefferson"},
  {id: "Jenkins", name: "Jenkins"},
  {id: "Johnson", name: "Johnson"},
  {id: "Jones", name: "Jones"},
  {id: "Lamar", name: "Lamar"},
  {id: "Lanier", name: "Lanier"},
  {id: "Laurens", name: "Laurens"},
  {id: "Lee", name: "Lee"},
  {id: "Liberty", name: "Liberty"},
  {id: "Lincoln", name: "Lincoln"},
  {id: "Long", name: "Long"},
  {id: "Lowndes", name: "Lowndes"},
  {id: "Lumpkin", name: "Lumpkin"},
  {id: "Macon", name: "Macon"},
  {id: "Madison", name: "Madison"},
  {id: "Marion", name: "Marion"},
  {id: "McDuffie", name: "McDuffie"},
  {id: "McIntosh", name: "McIntosh"},
  {id: "Meriwether", name: "Meriwether"},
  {id: "Miller", name: "Miller"},
  {id: "Mitchell", name: "Mitchell"},
  {id: "Monroe", name: "Monroe"},
  {id: "Montgomery", name: "Montgomery"},
  {id: "Morgan", name: "Morgan"},
  {id: "Murray", name: "Murray"},
  {id: "Muscogee", name: "Muscogee"},
  {id: "Newton", name: "Newton"},
  {id: "Oconee", name: "Oconee"},
  {id: "Oglethorpe", name: "Oglethorpe"},
  {id: "Paulding", name: "Paulding"},
  {id: "Peach", name: "Peach"},
  {id: "Pickens", name: "Pickens"},
  {id: "Pierce", name: "Pierce"},
  {id: "Pike", name: "Pike"},
  {id: "Polk", name: "Polk"},
  {id: "Pulaski", name: "Pulaski"},
  {id: "Putnam", name: "Putnam"},
  {id: "Quitman", name: "Quitman"},
  {id: "Rabun", name: "Rabun"},
  {id: "Randolph", name: "Randolph"},
  {id: "Richmond", name: "Richmond"},
  {id: "Rockdale", name: "Rockdale"},
  {id: "Schley", name: "Schley"},
  {id: "Screven", name: "Screven"},
  {id: "Seminole", name: "Seminole"},
  {id: "Spalding", name: "Spalding"},
  {id: "Stephens", name: "Stephens"},
  {id: "Stewart", name: "Stewart"},
  {id: "Sumter", name: "Sumter"},
  {id: "Talbot", name: "Talbot"},
  {id: "Taliaferro", name: "Taliaferro"},
  {id: "Tattnall", name: "Tattnall"},
  {id: "Taylor", name: "Taylor"},
  {id: "Telfair", name: "Telfair"},
  {id: "Terrell", name: "Terrell"},
  {id: "Thomas", name: "Thomas"},
  {id: "Tift", name: "Tift"},
  {id: "Toombs", name: "Toombs"},
  {id: "Towns", name: "Towns"},
  {id: "Treutlen", name: "Treutlen"},
  {id: "Troup", name: "Troup"},
  {id: "Turner", name: "Turner"},
  {id: "Twiggs", name: "Twiggs"},
  {id: "Union", name: "Union"},
  {id: "Upson", name: "Upson"},
  {id: "Walker", name: "Walker"},
  {id: "Walton", name: "Walton"},
  {id: "Ware", name: "Ware"},
  {id: "Warren", name: "Warren"},
  {id: "Washington", name: "Washington"},
  {id: "Wayne", name: "Wayne"},
  {id: "Webster", name: "Webster"},
  {id: "Wheeler", name: "Wheeler"},
  {id: "White", name: "White"},
  {id: "Whitfield", name: "Whitfield"},
  {id: "Wilcox", name: "Wilcox"},
  {id: "Wilkes", name: "Wilkes"},
  {id: "Wilkinson", name: "Wilkinson"},
  {id: "Worth", name: "Worth"},
]
