ERROR_DETAIL_CODES = {"IntegrityError": "data_integrity", "ProtectedError": "protected"}

SHELTER_ID = 223
ISHELTERS_CREATED_BY_IDS = [
    50673,
    56614,
    351150,
    282185,
    398337,
    50101,
    223562,
    221833,
    89176,
    122899,
    109829,
    128789,
    207664,
]

# region Counties
GA_COUNTIES = [
    "Appling",
    "Atkinson",
    "Bacon",
    "Baker",
    "Baldwin",
    "Banks",
    "Barrow",
    "Bartow",
    "Ben Hill",
    "Berrien",
    "Bibb",
    "Bleckley",
    "Brantley",
    "Brooks",
    "Bryan",
    "Bulloch",
    "Burke",
    "Butts",
    "Calhoun",
    "Camden",
    "Candler",
    "Carroll",
    "Catoosa",
    "Charlton",
    "Chatham",
    "Chattahoochee",
    "Chattooga",
    "Cherokee",
    "Clarke",
    "Clay",
    "Clayton",
    "Clinch",
    "Cobb",
    "Coffee",
    "Colquitt",
    "Columbia",
    "Cook",
    "Coweta",
    "Crawford",
    "Crisp",
    "Dade",
    "Dawson",
    "Decatur",
    "DeKalb",
    "Dodge",
    "Dooly",
    "Dougherty",
    "Douglas",
    "Early",
    "Echols",
    "Effingham",
    "Elbert",
    "Emanuel",
    "Evans",
    "Fannin",
    "Fayette",
    "Floyd",
    "Forsyth",
    "Franklin",
    "Fulton",
    "Gilmer",
    "Glascock",
    "Glynn",
    "Gordon",
    "Grady",
    "Greene",
    "Gwinnett",
    "Habersham",
    "Hall",
    "Hancock",
    "Haralson",
    "Harris",
    "Hart",
    "Heard",
    "Henry",
    "Houston",
    "Irwin",
    "Jackson",
    "Jasper",
    "Jeff",
    "Jefferson",
    "Jenkins",
    "Johnson",
    "Jones",
    "Lamar",
    "Lanier",
    "Laurens",
    "Lee",
    "Liberty",
    "Lincoln",
    "Long",
    "Lowndes",
    "Lumpkin",
    "Macon",
    "Madison",
    "Marion",
    "McDuffie",
    "McIntosh",
    "Meriwether",
    "Miller",
    "Mitchell",
    "Monroe",
    "Montgomery",
    "Morgan",
    "Murray",
    "Muscogee",
    "Newton",
    "Oconee",
    "Oglethorpe",
    "Paulding",
    "Peach",
    "Pickens",
    "Pierce",
    "Pike",
    "Polk",
    "Pulaski",
    "Putnam",
    "Quitman",
    "Rabun",
    "Randolph",
    "Richmond",
    "Rockdale",
    "Schley",
    "Screven",
    "Seminole",
    "Spalding",
    "Stephens",
    "Stewart",
    "Sumter",
    "Talbot",
    "Taliaferro",
    "Tattnall",
    "Taylor",
    "Telfair",
    "Terrell",
    "Thomas",
    "Tift",
    "Toombs",
    "Towns",
    "Treutlen",
    "Troup",
    "Turner",
    "Twiggs",
    "Union",
    "Upson",
    "Walker",
    "Walton",
    "Ware",
    "Warren",
    "Washington",
    "Wayne",
    "Webster",
    "Wheeler",
    "White",
    "Whitfield",
    "Wilcox",
    "Wilkes",
    "Wilkinson",
    "Worth",
]

# endregion

AAU_JOB_TITLES = [
    "AAU Board Member",
    "AAU Officer",
    "AAU Staff Member",
    "AAU Team Lead",
    "AAU Volunteer",
]

# region Teams
AAU_TEAMS = {
    "Admin": [
        {
            "name": "Customer Service",
            "description": "Includes main phone, email, and joinus",
        },
        {
            "name": "Customer Service - Assistance Team",
            "description": None,
        },
        {
            "name": "Email Administration",
            "description": None,
        },
        {
            "name": "Finance & Executive Team",
            "description": None,
        },
        {
            "name": "Information Technology",
            "description": None,
        },
        {
            "name": "Ishelters Administration",
            "description": None,
        },
        {
            "name": "Maddie's Fund Training",
            "description": None,
        },
        {"name": "Moves", "description": None, "email": "moves@auu.org"},
        {
            "name": "PetFinder & Adopt-a-Pet",
            "description": None,
        },
        {"name": "Prayer Team", "description": None},
        {"name": "Puppy Team", "description": None},
        {"name": "Vet Records", "description": None},
    ],
    "Apps": [
        {"name": "Volunteers", "description": None},
        {"name": "Foster - Dog", "description": None},
        {"name": "App Uploaders", "description": None},
        {"name": "Adoption - Dog", "description": None},
    ],
    "Cats": [
        {"name": "Cat Records", "description": None},
        {"name": "Cat Vetting", "description": None},
        {"name": "Cat Foster Apps", "description": None},
        {"name": "Cat Adoption Apps", "description": None},
        {"name": "Petco Cat Habitat", "description": None},
    ],
    "Foster Support": [
        {"name": "Boarding Admin", "description": None},
        {"name": "Boarding Buddies", "description": None},
        {"name": "Foster Home Checks", "description": None},
        {"name": "Foster Home Rechecks", "description": None},
        {"name": "Foster Placements", "description": None},
        {"name": "Mentors", "description": None},
        {"name": "Supplies Team", "description": None},
        {"name": "Training", "description": None},
    ],
    "Fundraising": [
        {"name": "Events", "description": None},
        {"name": "Grant Writer", "description": None},
        {"name": "Social Media Team", "description": None},
        {"name": "Donations Support & Acknowledgement", "description": None},
    ],
    "Intakes": [
        {"name": "Intakes Coordinator", "description": None},
        {"name": "Pulls Coordinator", "description": None},
        {"name": "Returns Coordinator", "description": None},
        {"name": "Shelter Liaison", "description": None},
        {"name": "Temperament Tests", "description": None},
        {"name": "Transport Coordinators", "description": None},
        {"name": "Transporter", "description": None},
    ],
    "Outreach": [
        {"name": "Education and Community Outreach", "description": None},
    ],
    "Vet": [
        {"name": "Heartworm Team", "description": None},
        {"name": "Intake Vetting", "description": None},
        {"name": "Pharmacy", "description": None},
        {"name": "Prevents", "description": None},
        {"name": "Spay/Neuter Team", "description": None},
        {"name": "Vet Cases", "description": None},
        {"name": "Vet Team", "description": None},
    ],
}
# endregion
