# Generated by Django 5.1.1 on 2024-10-30 16:54

from django.db import migrations
from django.db.utils import IntegrityError
from django.contrib.auth.models import Group as G


# https://eshlox.net/2019/07/27/adding-groups-via-django-db-migration-script-and-assigning-a-group-to-all-existing--users
def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Group: G = apps.get_model("auth", "Group")

    # region Create Groups
    try:
        Group.objects.using(db_alias).create(name="Administrator")
    except IntegrityError:
        pass

    try:
        Group.objects.using(db_alias).create(name="Editor")
    except IntegrityError:
        pass

    try:
        Group.objects.using(db_alias).create(name="Viewer")
    except IntegrityError:
        pass
    # endregion


def unapply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Group = apps.get_model("auth", "Group")
    Group.objects.using(db_alias).filter(
        name__in=["Administrator", "Editor", "Viewer"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=apply_migration, reverse_code=unapply_migration)
    ]
