# Generated by Django 5.1.1 on 2024-11-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_volunteerchildren_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='active_status_change_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='has_maddie_certifications',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='location',
        ),
        migrations.AddField(
            model_name='volunteerskill',
            name='type',
            field=models.CharField(default='skill', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerchildren',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteerpet',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
